# Generated by Django 5.2.9 on 2026-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('gmail_oauth', 'Gmail OAuth'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('smtp', 'SMTP Credentials'), ('custom', 'Custom'), ('ai_offline', 'Offline AI (Ollama)'), ('google_calendar', 'Google Calendar OAuth'), ('google_calendar_oauth', 'Google Calendar (Legacy)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='action_type',
            field=models.CharField(choices=[('http_request', 'HTTP Request'), ('webhook', 'Webhook Trigger'), ('schedule', 'Schedule Trigger'), ('manual', 'Manual Trigger'), ('email', 'Send Email'), ('code', 'Code (Python)'), ('condition', 'IF / Condition'), ('delay', 'Delay'), ('merge', 'Merge'), ('set_variables', 'Set Variables'), ('subworkflow', 'Sub-Workflow'), ('transform', 'Transform Data'), ('loop', 'Loop'), ('google_calendar', 'Google Calendar')], max_length=50),
        ),
    ]
