# Generated by Django 5.2.9 on 2026-01-26 12:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_alter_credential_type_whatsappconversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_human_controlled', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('command', 'Command'), ('photo', 'Photo'), ('document', 'Document'), ('audio', 'Audio'), ('voice', 'Voice'), ('other', 'Other')], default='text', max_length=20)),
                ('text', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(default='en_US', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('content_schema', models.JSONField(blank=True, default=dict, help_text='Cached structure of the template')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='whatsappconversation',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='executionlog',
            name='workflows_e_executi_93846b_idx',
        ),
        migrations.RemoveIndex(
            model_name='executionlog',
            name='workflows_e_node_ex_fd8c88_idx',
        ),
        migrations.RemoveIndex(
            model_name='executionlog',
            name='workflows_e_tenant__400547_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappconversation',
            name='workflows_w_credent_db9e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappconversation',
            name='workflows_w_credent_37f193_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessage',
            name='workflows_w_convers_20dadb_idx',
        ),
        migrations.RemoveIndex(
            model_name='whatsappmessage',
            name='workflows_w_message_ad2404_idx',
        ),
        migrations.AlterUniqueTogether(
            name='whatsappconversation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='executionlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='raw_payload',
        ),
        migrations.RemoveField(
            model_name='whatsappusage',
            name='last_reset_at',
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='24h from last user message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='is_human_controlled',
            field=models.BooleanField(default=False, help_text='If true, AI should pause'),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='last_business_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappconversation',
            name='user_phone_number',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='credential',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='workflows.credential'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='error_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('image', 'Image'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('interactive', 'Interactive'), ('other', 'Other')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='meta_message_id',
            field=models.CharField(blank=True, help_text='wamid...', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='user_phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='User phone for quick lookups', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappusage',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('telegram_bot', 'Telegram Bot'), ('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('smtp', 'SMTP'), ('ai_offline', 'Offline AI (Ollama)'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('meta_whatsapp', 'Meta WhatsApp'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='whatsappconversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='workflows.whatsappconversation'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(db_index=True, default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappusage',
            name='conversation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['execution', 'level'], name='workflows_e_executi_d3dd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['node_execution'], name='workflows_e_node_ex_8aaa16_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['credential', 'user_phone_number'], name='workflows_w_credent_377e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['expires_at'], name='workflows_w_expires_630772_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['credential', 'timestamp'], name='workflows_w_credent_8ce1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['meta_message_id'], name='workflows_w_meta_me_33a59f_idx'),
        ),
        migrations.AddField(
            model_name='telegramconversation',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_conversations', to='workflows.credential'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflows.telegramconversation'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='workflows.credential'),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='workflows.credential'),
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='conversation_start_at',
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='monthly_bucket',
        ),
        migrations.RemoveField(
            model_name='whatsappconversation',
            name='phone_number',
        ),
        migrations.AddIndex(
            model_name='telegramconversation',
            index=models.Index(fields=['credential', 'chat_id'], name='workflows_t_credent_bde264_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramconversation',
            index=models.Index(fields=['credential', 'user_id'], name='workflows_t_credent_41cc40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegramconversation',
            unique_together={('credential', 'chat_id')},
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['conversation', 'created_at'], name='workflows_t_convers_957bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['chat_id', 'created_at'], name='workflows_t_chat_id_32af73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsapptemplate',
            unique_together={('credential', 'name', 'language')},
        ),
    ]
