# Generated by Django 5.2.10 on 2026-01-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_executionlog_tenant_alter_node_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom theme configuration: colors, glassmorphism, etc.'),
        ),
    ]
