# Generated by Django 5.2.10 on 2026-02-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_userprofile_theme_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('telegram_bot', 'Telegram Bot'), ('gmail', 'Gmail'), ('google_oauth', 'Google OAuth (Drive/Sheets/YouTube)'), ('discord_bot', 'Discord Bot'), ('google_calendar', 'Google Calendar'), ('smtp', 'SMTP'), ('ai_offline', 'Offline AI (Ollama)'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('meta_whatsapp', 'Meta WhatsApp'), ('custom', 'Custom')], max_length=50),
        ),
    ]
