# Generated by Django 5.2.11 on 2026-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_credential_status_alter_credential_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('smtp', 'SMTP'), ('ollama', 'Ollama'), ('telegram', 'Telegram'), ('telegram_bot', 'Telegram Bot'), ('whatsapp', 'WhatsApp'), ('meta_whatsapp', 'Meta WhatsApp'), ('internal', 'Internal'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('telegram_bot', 'Telegram Bot'), ('meta_whatsapp', 'WhatsApp Business'), ('gmail_oauth', 'Gmail OAuth'), ('smtp_server', 'SMTP Server'), ('general_api_key', 'General API Key'), ('ollama_local', 'Ollama (Local AI)'), ('telegram', 'Telegram (Alias)'), ('whatsapp', 'WhatsApp (Alias)'), ('gmail', 'Gmail (Alias)'), ('google_oauth', 'Google OAuth (Legacy)'), ('smtp', 'SMTP (Alias)'), ('ollama', 'Ollama (Alias)'), ('ai_offline', 'AI Offline (Legacy)'), ('api_key', 'API Key (Legacy)'), ('discord_bot', 'Discord Bot'), ('google_calendar', 'Google Calendar'), ('google_sheets', 'Google Sheets'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('custom', 'Custom')], max_length=50),
        ),
    ]
