# Generated by Django 5.2.11 on 2026-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='role',
            field=models.CharField(choices=[('user', 'User')], max_length=10),
        ),
    ]
