# Generated by Django 5.2.10 on 2026-01-25 18:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_credential_type_alter_node_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='credential',
            name='unique_credential_per_user_and_type',
        ),
        migrations.RemoveIndex(
            model_name='credential',
            name='workflows_c_owner_i_0cd4c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='credential',
            name='workflows_c_tenant__6192ef_idx',
        ),
        migrations.AddField(
            model_name='credential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('smtp', 'SMTP'), ('ollama', 'Ollama'), ('internal', 'Internal'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('smtp', 'SMTP'), ('ai_offline', 'Offline AI (Ollama)'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['owner', 'provider', 'type'], name='workflows_c_owner_i_216962_idx'),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['tenant', 'provider', 'type'], name='workflows_c_tenant__a3ada0_idx'),
        ),
        migrations.AddConstraint(
            model_name='credential',
            constraint=models.UniqueConstraint(fields=('owner', 'provider', 'type'), name='unique_credential_per_user_svc'),
        ),
    ]
