# Generated by Django 5.2.9 on 2026-01-26 06:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_remove_credential_unique_credential_per_user_and_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('smtp', 'SMTP'), ('ai_offline', 'Offline AI (Ollama)'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('meta_whatsapp', 'Meta WhatsApp'), ('custom', 'Custom')], max_length=50),
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=50)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('conversation_start_at', models.DateTimeField(blank=True, help_text='Start of 24h window', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Is within 24h free/service window')),
                ('monthly_bucket', models.CharField(db_index=True, help_text='YYYY-MM for aggregation', max_length=7)),
                ('message_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='workflows.credential')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_id', models.CharField(help_text='Meta Message ID (wamid)', max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflows.whatsappconversation')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('conversation_count', models.IntegerField(default=0, help_text='Number of initiated conversations this month')),
                ('last_reset_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_usage', to='workflows.credential')),
            ],
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['credential', 'phone_number'], name='workflows_w_credent_db9e54_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['credential', 'monthly_bucket'], name='workflows_w_credent_37f193_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappconversation',
            unique_together={('credential', 'phone_number')},
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='workflows_w_convers_20dadb_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['message_id'], name='workflows_w_message_ad2404_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappusage',
            unique_together={('credential', 'month')},
        ),
    ]
