# Generated by Django 5.2.10 on 2026-01-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_telegramconversation_telegrammessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='node',
            name='action_type',
            field=models.CharField(choices=[('http_request', 'HTTP Request'), ('webhook', 'Webhook Trigger'), ('schedule', 'Schedule Trigger'), ('manual', 'Manual Trigger'), ('email', 'Send Email'), ('code', 'Code (Python)'), ('condition', 'IF / Condition'), ('delay', 'Delay'), ('merge', 'Merge'), ('set_variables', 'Set Variables'), ('subworkflow', 'Sub-Workflow'), ('transform', 'Transform Data'), ('loop', 'Loop'), ('google_calendar', 'Google Calendar'), ('telegram_trigger', 'Telegram Trigger'), ('telegram_send', 'Telegram Send'), ('ai_agent', 'AI Agent'), ('model_openai', 'OpenAI Model'), ('tool_websearch', 'Web Search Tool'), ('email_trigger', 'Email Trigger'), ('whatsapp_trigger', 'WhatsApp Trigger'), ('whatsapp_send', 'WhatsApp Send'), ('chat_response', 'Chat Response')], max_length=50),
        ),
    ]
