# Generated by Django 5.2.11 on 2026-02-06 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_organization_tenant_alter_credential_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SAVE', 'Save'), ('PUBLISH', 'Publish'), ('ROLLBACK', 'Rollback'), ('DELETE', 'Delete'), ('CREATE', 'Create')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'created_at'], name='workflows_w_workflo_210063_idx')],
            },
        ),
    ]
