# Generated by Django 5.2.10 on 2026-02-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_workflowhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='status',
            field=models.CharField(default='not_configured', help_text='Configured status of the credential', max_length=20),
        ),
        migrations.AlterField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth2'), ('telegram', 'Telegram Bot'), ('telegram_bot', 'Telegram Bot (Legacy)'), ('gmail', 'Gmail'), ('gmail_oauth', 'Gmail OAuth'), ('google_oauth', 'Google OAuth (Legacy)'), ('discord_bot', 'Discord Bot'), ('google_calendar', 'Google Calendar'), ('smtp', 'SMTP'), ('ollama', 'Ollma (AI Offline)'), ('ai_offline', 'Offline AI (Ollama - Legacy)'), ('basic_auth', 'Basic Auth'), ('bearer_token', 'Bearer Token'), ('whatsapp', 'WhatsApp Business'), ('meta_whatsapp', 'Meta WhatsApp (Legacy)'), ('custom', 'Custom'), ('general_api_key', 'General API Key')], max_length=50),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
