# Generated by Django 5.2.11 on 2026-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_alter_credential_provider_alter_credential_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconversation',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
